default:
  outputs:

    dev: # User-Password config
      type: snowflake
      account: ZLRZGBX-WMC50466
      user: DBT_CLOUD_DEV
      password: Pri1thvimarwadi@2004
      role: TRANSFORMER_DEV
      database: DEV
      warehouse: TRANSFORMING_DEV
      schema: dbt_pmarwadi
      threads: 2
      client_session_keep_alive: False

  target: dev